- installer.cfg
here is my first humble contribution
> added a small comment. just a beginning for issue #1

- README.rst
- installer.cfg
tips about debug and freshclam
> Documentation

- modoboa_installer/database.py
* Add mariadb-server package to the yum installation
* Add root password initial settings ("post"seed fashion)
* Handle centos "mysql" service name according to MariaDB switch
* add modoboa@localhost in order to give access
> Centos7 / Mariadb fixes

- modoboa_installer/scripts/dovecot.py
- modoboa_installer/scripts/files/dovecot/conf.d/10-auth.conf
- modoboa_installer/scripts/files/dovecot/conf.d/auth-sql.conf.ext
- modoboa_installer/scripts/files/dovecot/dovecot-sql-master-mysql.conf.ext.tpl
- modoboa_installer/scripts/files/dovecot/dovecot-sql-master-postgres.conf.ext.tpl
> Enable dovecot master users.

- modoboa_installer/scripts/files/dovecot/conf.d/auth-sql.conf.ext
- modoboa_installer/scripts/files/dovecot/dovecot-sql-mysql.conf.ext.tpl
- modoboa_installer/scripts/files/dovecot/dovecot-sql-postgres.conf.ext.tpl
> Enabled prefetching.

- README.rst
- installer.cfg
- modoboa_installer/python.py
- modoboa_installer/scripts/automx.py
- modoboa_installer/scripts/base.py
- modoboa_installer/scripts/files/automx/automx.conf.tpl
- modoboa_installer/scripts/files/nginx/automx.conf.tpl
- modoboa_installer/scripts/files/nginx/modoboa.conf.tpl
- modoboa_installer/scripts/files/uwsgi/automx.ini.tpl
- modoboa_installer/scripts/files/uwsgi/modoboa.ini.tpl
- modoboa_installer/scripts/modoboa.py
- modoboa_installer/scripts/nginx.py
- modoboa_installer/scripts/uwsgi.py
- modoboa_installer/system.py
- run.py
> Added automx support.

- installer.cfg.default
- modoboa_installer/utils.py
- run.py
see #118
Also generate random passwords instead of the old 'password' default.
> Create config file from template.

- modoboa_installer/scripts/modoboa.py
> Added dbuser.

- modoboa_installer/config_dict_template.py
- modoboa_installer/scripts/base.py
- modoboa_installer/scripts/files/postfix/main.cf.tpl
- modoboa_installer/scripts/files/postwhite/crontab.tpl
- modoboa_installer/scripts/postfix.py
- modoboa_installer/scripts/postwhite.py
- tests.py
> Added postwhite support.

- modoboa_installer/config_dict_template.py
- modoboa_installer/python.py
- modoboa_installer/scripts/dovecot.py
- modoboa_installer/scripts/files/dovecot/conf.d/10-master.conf.tpl
- modoboa_installer/scripts/files/radicale/config.tpl
- modoboa_installer/scripts/files/radicale/supervisor.tpl
- modoboa_installer/scripts/modoboa.py
- modoboa_installer/scripts/nginx.py
- modoboa_installer/scripts/radicale.py
- run.py
> Added Radicale setup.

- README.rst
Highlighting a few pain points I found when installing this lovely piece of software - a 1GB VPS saw builds failing, and I had to rebuild the VPS a few times until I discovered the passwords were the problem
> Clarified some points in README

- run.py
> Fixed A record definition.

- README.rst
- modoboa_installer/scripts/__init__.py
- modoboa_installer/scripts/amavis.py
- modoboa_installer/scripts/automx.py
- modoboa_installer/scripts/base.py
- modoboa_installer/scripts/modoboa.py
- modoboa_installer/scripts/nginx.py
- modoboa_installer/scripts/postfix.py
- modoboa_installer/scripts/radicale.py
- modoboa_installer/scripts/spamassassin.py
- modoboa_installer/ssl.py
- modoboa_installer/utils.py
- run.py
- tests.py
> Installer upgrade mode.

- modoboa_installer/database.py
- modoboa_installer/scripts/postwhite.py
- modoboa_installer/ssl.py
> Add missing packages

- modoboa_installer/scripts/dovecot.py
- modoboa_installer/scripts/files/dovecot/conf.d/10-master.conf.tpl
Fixes #modoboa/modoboa#2603 for new users.
> Change stats permission to allow doveadm pw command 

- modoboa_installer/config_dict_template.py
Update default value to have one master one child process at minimum.
> Update config_dict_template.py for default max_servers value

- modoboa_installer/config_dict_template.py
> fixed constants import

- modoboa_installer/scripts/modoboa.py
There is a parenthesis that shouldn't be there. (modoboa/modoboa#2673)
> fixed super call in modoboa's script

- modoboa_installer/config_dict_template.py
- modoboa_installer/scripts/fail2ban.py
- modoboa_installer/scripts/files/fail2ban/filter.d/modoboa-auth.conf.tpl
- modoboa_installer/scripts/files/fail2ban/jail.d/modoboa.conf.tpl
- run.py
To prevent brute force attacks on authentication endpoints.
> Added fail2ban setup

- modoboa_installer/scripts/automx.py
Relates to https://github.com/modoboa/modoboa-installer/issues/475
> Fix automx

- modoboa_installer/compatibility_matrix.py
- modoboa_installer/config_dict_template.py
- modoboa_installer/scripts/modoboa.py
Removed modoboa-pdfcredentials from default installation, Prevent users from installing merged extensions
> Updated for 2.1

- modoboa_installer/scripts/files/nginx/automx.conf.tpl
- modoboa_installer/scripts/files/nginx/modoboa.conf.tpl
Loading seems quicker with http2.
> Added http2 for nginx

- README.rst
- modoboa_installer/config_dict_template.py
- modoboa_installer/ssl.py
- modoboa_installer/utils.py
- run.py
- Allow user to set a pre-generated SSL cert (manual certificate added)
- Added information regarding LetsEncrypt ToS
> Added custom tls cert support

- modoboa_installer/ssl.py
> Added renewal deploy hook to reload services.

- modoboa_installer/python.py
- modoboa_installer/scripts/automx.py
- modoboa_installer/scripts/modoboa.py
- modoboa_installer/scripts/radicale.py
> Compat. with Ubuntu 24.04

- modoboa_installer/scripts/files/postfix/main.cf.tpl
> Removed SORBS dnsbl

- modoboa_installer/scripts/files/postfix/main.cf.tpl
PR: Disabling old versions of TLS and obsolete Ciphers
> feature: improve security on postfix

- .github/workflows/installer.yml
- modoboa_installer/scripts/files/radicale/config.tpl
- modoboa_installer/scripts/radicale.py
dovecot auth is now part of Radicale
> Updated Radicale config
