modoboa/modoboa-installer

- README.rst
If /tmp is mounted with noexec, autoconf will fail.
> Mention that /tmp has to be executable

- modoboa_installer/ssl.py
The @ecobytes instance showed a misbehaviour concerning TLS certificates which had been set in instance.cfg.
Ultimately 89cdc314ea9ad93d7951d1800e525f85ec47eaac#diff-c226f84131b50059e044a64c41fe782c added a logic which would not account for preconfigured TLS certificates anymore.
This commit introduces a small change to revive usage of third-party certificates without overwriting their configuration options.
> update SSL logic to accomodate pregenerated certificates

- modoboa_installer/scripts/nginx.py
- modoboa_installer/scripts/postfix.py
http://security.stackexchange.com/questions/95178/diffie-hellman-parameters-still-calculating-after-24-hours suggests to add the `-dsaparam` to the OpenSSL commandline for unarbitrarily long running Diffie-Hellman parameters generation.
> Make OpenSSL use less computing power, closes #87

- modoboa_installer/utils.py
string.asciletters is not locale-dependent but exists both in python2 and 3
so that avoids the script to break in python3 at a minor expense in my opinion
Current behavior before PR: 
```
string.letters + string.digits) for _ in range(length))
AttributeError: module 'string' has no attribute 'letters'
```
Desired behavior after PR is merged: script run fine in both python 2 and 3
> Changed string.letters to string.asciletters in utils

- modoboa_installer/compatibility_matrix.py
- modoboa_installer/scripts/modoboa.py
- modoboa_installer/utils.py
- run.py
A new option to choose a different Modoboa version to install. Due to an issue with the deploy command (see https://github.com/modoboa/modoboa/issues/1177), only versions >= 1.8.1 will be concerned.
see #138
> Added support for modoboa version selection.

- modoboa_installer/scripts/files/automx/automx.conf.tpl
Fix typo which breaks autodiscover
See issue #154
automx.conf.tpl
Typo in default installed config breaks autodiscover
Autodiscover setup works without searching for bugs in default config
> Fix typo in automx.conf.tpl

- modoboa_installer/scripts/files/dovecot/conf.d/10-auth.conf
Fix the auth_mechanisms setting in dovecot/10-auth.conf. Closes #175
Outlook on the Mac cannot send mail
On new installs, Outlook on the Mac can send mail
> Fix the auth_mechanisms setting in dovecot/10-auth.conf. Closes #175

- modoboa_installer/scripts/files/opendkim/opendkim.conf.tpl
If logging is enabled (see Syslog below), requests that the results of evaluation of all signatures that were at least partly intact (i.e., the "d=", "s=", and "b=" tags could be extracted).
Not revelent
Not revelent
> opendkim: add LogResults = Yes

- modoboa_installer/scripts/opendkim.py
Fixes issue #207 
On Ubuntu 16.04, the file `/etc/default/opendkim` is not edited, and specifies an incorrect socket for OpenDKIM to listen to. As a result, Postfix is unable to connect to OpenDKIM.
The correct port 12345 is specified in `/etc/default/opendkim`.
> Update /etc/default/opendkim on Debian-based system post installation.

- modoboa_installer/scripts/files/postfix/master.cf.tpl
Fixes #237 - the ```-o smtpd_recipient_restrictions=``` overrides the config in ```main.cf``` and causes Postfix to reject mail from some clients
Postfix rejects mail from some mail clients (like Windows Mail and Thunderbird), while simultaneously complaining that there is no rejection of recipients.
The mail clients can send email
> Fixed recipient restrictions

- modoboa_installer/scripts/files/nginx/automx.conf.tpl
- modoboa_installer/scripts/nginx.py
Description of the issue/feature in this PR addresses:
- Modification of location in nginx config.
- Add missing `root /srv/automx/instance;`.
Don't catch lowercase et uppercase  in `autodiscover/autodiscover.xml`
> Nginx vhost template update for autodiscover

- modoboa_installer/scripts/opendkim.py
There are 2 open PR's related to this #217, #262, and pending for a long time.
The opendkim systemd start script does not wait for the DB to start
The opendkim systemd start script will wait for the DB to start first.
It will handle both deb & rpm distributions, and mysql and postgresql>
I just tried to handle both linux distributions and the database service naming (mysql, mysql, postgresql)
I have deployed succesfully from this branch on Centos 7.7 droplet, with postgresql.
I have run into separate  issues due:
- SELinux (I run with SELinux enabled),
- the opendkim table in postgres had no rows, which prevented opendkim start
- letsencrypt renewals were failing, certbot could not find nginx (due to cron PATH)
- now letsencrypt renewalls work, but got blocked by letsencrypt due to rate …
> Pr dkim set db prio for deb & rpm, for mysql & postgres

- modoboa_installer/scripts/opendkim.py
This is an extension of @oscarcarlsson's [PR 217](https://github.com/modoboa/modoboa-installer/pull/217) which adds a differentiation between PostgreSQL and MySQL. Furthermore, it fixes a bug in the regular expression (`\1` -> `$1`).
Be aware that it may be necessary to use `mysqld.service` on RPM platforms ([source](https://dev.mysql.com/doc/mysql-linuxunix-excerpt/5.7/en/using-systemd.html)). Please decide if this particular case should be supported, too.
> Make sure OpenDKIM is started after PostgreSQL/MySQL

- modoboa_installer/utils.py
Description of the issue/feature this PR addresses:  
This fixes issue the first error in #314 since Ubuntu 20.04 uses Python 3.8.
Current behavior before PR:  
The installer does not run on python 3.8.
Desired behavior after PR is merged:  
Installer runs on all versions of python including 3.8
This was tested on: 
- Ubuntu 18/Python 3.6.9:  Result 'ubuntu'
- Ubuntu 20/Python 3.8.2:  Result 'ubuntu'
- Debian 10/Python 3.7.3:  Result 'debian'
- MacOS 10.15.4/Python 3.7.5:  Result 'unknown'
> Use bistro package in utils.dist_name if it exists

- modoboa_installer/ssl.py
On Debian 10, dist_info() returns a lower case "debian" and the installation of certbot fails.
I changed the installation method to check the distribution name in case insensitive way.
```
Starting...
Generating new certificate using letsencrypt
Failed to install certbot, aborting.
```
```
Starting...
Generating new certificate using letsencrypt
Installing amavis
Installing spamassassin
...
```
> Fixed dist_info() case sensitivity for certbot installation

- modoboa_installer/scripts/modoboa.py
On Debian-based systems, since commit 6fdf57b, the Redis server is not started during execution of the installer.
Redis server not started, so not available after installation.
Redis server started.
> Ensure redis server is started

- modoboa_installer/database.py
Fixed change introduced with #428. The bug comes from the fact that user disabled db install in the config. This will require a more in depth fix.
> removed libmysqlclient-dev

- modoboa_installer/scripts/files/postfix/main.cf.tpl
Since 2021, spamhaus now requires that your dns resolver has a non-generic rDns set up. 
Since modoboa doesn't set one as MIAB could do, spamhaus has high chance to send back 127.255.255.254 to a lot of users. Postifx should only treat answer between 1 and 11.
> mitigate false spamhaus reject

- modoboa_installer/config_dict_template.py
A bunch of user are reporting errors, likely due to the fact that by default max_server is at one, so ounce the child number has been achieved (20 by default) the process is terminated, ending by a queue file error.
> Set $max_server to 2 to avoid amavis crash

- modoboa_installer/scripts/dovecot.py
- modoboa_installer/scripts/files/dovecot/conf.d/10-ssl-keys.try.tpl
- modoboa_installer/scripts/files/dovecot/conf.d/10-ssl.conf.tpl
Fixes modoboa/modoboa#2570. It also updates ssl_protocols to ssl_min_protocol (https://doc.dovecot.org/installation_guide/upgrading/from-2.2-to-2.3/).
> Fixes ssl permission error, updated ssl_protocol parameter

- modoboa_installer/scripts/dovecot.py
In precedent PR (#445) dovecot configuration syntax was updated, but I forgot to update the right part.
`TLSv1` is the [new way of saying](https://doc.dovecot.org/settings/core/?highlight=ssl_min_protocol#core_setting-ssl_min_protocol) `!SSLv3` with `ssl_min_protocol`
> fixed ssl_min_protocol setting

- modoboa_installer/utils.py
Change proposed with issue : modoboa/modoboa#2153
Permissions for automated generated config file are now set to 600 with this PR.
> tighter config file permission

- modoboa_installer/scripts/files/dovecot/conf.d/10-ssl.conf.tpl
`!include_try` does not take a `=`
> fix typo in dovecot configuration file

- modoboa_installer/scripts/files/modoboa/crontab.tpl
- modoboa_installer/scripts/modoboa.py
Avoid public api to crash due to high amount of clients connecting at the same time.
> randomize api call time

- modoboa_installer/scripts/postwhite.py
Fixed bug introduced with backup/restore feature. Postwhite config file was not being copied anymore.
> Postwhite conf file not being copied 

- modoboa_installer/scripts/modoboa.py
Make use of the mkdir_safe() function when applying settings from the extensions upon install. This will prevent issues with webmail (#461) .
> Create subfolder on modoboas extensions install

- modoboa_installer/scripts/opendkim.py
When restoring from backup, dkim keys are restored as root, whereas opendkim needs it to be its own user.
> fixed dkim permissions

- run.py
This simple change makes it easier for new users to add the DNS records they need for there Modoboa installation.
The original issue was that people had a hard time understanding what the `Name` for the `MX` record should be. The `@` displays that it is the root of the domain; which people are able to comprehend better.
Does not display a `@` symbol in front of the `MX` record.
Displays an `@` symbol before the ` IN MX mail.example.com.`
> Make DNS understaind easier for users

- modoboa_installer/scripts/dovecot.py
Resolves modoboa/modoboa#2570
When dovecot first starts up, `root` reads the dovecot conf and is able to read and load the keys in `/etc/dovecot/conf.d/10-ssl-keys.try` Inside that file, it can read the private key (that only root has permissions to read)
However when we try delete a user, `doveconf` tries to read the config (to find the user's mailbox) `doveconf` MUST fail to open `10-ssl-keys.try`, which is fine, because `10-ssl.conf` says
```
!include_try /etc/dovecot/conf.d/10-ssl-keys.try
```
So if `doveconf` can't open `10-ssl-keys.try` it will will keep going. However if `doveconf` can read `10-ssl-keys.try` then `doveconf` crashes saying something like:
```
Failed to retrieve mailbox location (b doveconf: Fatal: Error in configuration file /etc/dovecot/conf.d/10-ssl-keys.try line …
```
> Fixed permissions of /etc/dovecot/conf.d/10-ssl-keys.try to resolve issue #2570

- modoboa_installer/scripts/files/nginx/automx.conf.tpl
http2 should only be issued for 443
Wrong configuration
All working the right way
> Fix http2 wrong port

- modoboa_installer/database.py
- modoboa_installer/scripts/files/amavis/amavis_mysql_2.13.X.sql
- modoboa_installer/scripts/files/amavis/amavis_postgres_2.13.X.sql
Currently, modoboa install fails on debian 12
Install fails
Install on debian12 succeed
I made some little changes to make installer work on debian12. Tested just once on my new server it seems to work, but should be tested more before merge, if there are some volounteers :) 
Changes:
- Copy amavis 2.12.X files to 2.13.X files
- Change some packages for which names change, or include "12" version like "11" version
There is still a bug due to python 3.11 but it's related to modoboa core (I have a fix), so I will make a MR here too
> Add support of Debian 12

- modoboa_installer/package.py
Fixes apt-get install when package already exists with an old config file. The updated code automatically installs the package-maintainer's version of any config files that come with the package.
Resolves issue [ Upgrade freezes while installing nginx #538 ](https://github.com/modoboa/modoboa-installer/issues/538)
`./run.py --upgrade <your domain>`
**Before**
**This is the reason**
**After my patch**
**I restored the VM to the point prior to the attempted upgrade.**
**Re-attempt the upgrade.**
**nginx installs successfully!**
> Fixed frozen apt install during Modoboa upgrade when package already installed with old config file

- modoboa_installer/package.py
Fixes installer compatibility errors with LMDE by adding "linuxmint" to the list of Debian distros.
Fails to install on LMDE
Installs on LMDE
Note: Although this fixes the issue for LMDE, the true way to fix this for _all_ Debian derivatives is to implement the "ID_LIKE" parameter from /etc/os-release. 
Note 2: This fix has _not_ been tested on ubuntu or base debian.
> LMDE compatability

- README.rst
- modoboa_installer/compatibility_matrix.py
- modoboa_installer/scripts/modoboa.py
- run.py
> Prevent installation of incompatible extensions

- modoboa_installer/scripts/files/postfix/master.cf.tpl
Add missing headers for mail from sasl auth'd users and mynetworks.
In our environment we've got quite a number of scanners/MFC printers (and some other devices) that send mail but don't supply normal RFC required headers - namely date.
Tweaking the master.cf fixes this in a way that I don't think would adversely impact anyone.
Missing headers, like date would cause the file to show up in quarantined list for amavis (though I don't think any in our case actually got quarantined - though I'm not positive.)
This simply adds missing header fields required by RFC, though only for clients who have done sasl or are part of my-networks, so this should be safe from breaking DKIM …
> Update master.cf.tpl - add missing headers

- README.rst
- run.py
> Added skipping mail backup in backup process

- modoboa_installer/database.py
- modoboa_installer/scripts/modoboa.py
#561 and #576
Issued warnings:
```
/root/modoboa-installer/modoboa_installer/database.py:106: SyntaxWarning: invalid escape sequence '\|'
"psql -lqt | cut -d \| -f 1 | grep -w {} | wc -l"
/root/modoboa-installer/modoboa_installer/scripts/modoboa.py:104: SyntaxWarning: invalid escape sequence '\<'
req_version = req_version.replace("<", "\<")
/root/modoboa-installer/modoboa_installer/scripts/modoboa.py:105: SyntaxWarning: invalid escape sequence '\>'
req_version = req_version.replace(">", "\>")
```
No warnings.
> Fix #561 and #576
